In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
pd.options.display.max_rows = 1000
pd.options.display.max_columns = 200

In [2]:
df = pd.read_csv('preco_casas.csv',sep=',')

In [3]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object


In [4]:
df.describe(include='all')

Id   MSSubClass MSZoning  LotFrontage        LotArea Street  \
count   1460.000000  1460.000000     1460  1201.000000    1460.000000   1460   
unique          NaN          NaN        5          NaN            NaN      2   
top             NaN          NaN       RL          NaN            NaN   Pave   
freq            NaN          NaN     1151          NaN            NaN   1454   
mean     730.500000    56.897260      NaN    70.049958   10516.828082    NaN   
std      421.610009    42.300571      NaN    24.284752    9981.264932    NaN   
min        1.000000    20.000000      NaN    21.000000    1300.000000    NaN   
25%      365.750000    20.000000      NaN    59.000000    7553.500000    NaN   
50%      730.500000    50.000000      NaN    69.000000    9478.500000    NaN   
75%     1095.250000    70.000000      NaN    80.000000   11601.500000    NaN   
max     1460.000000   190.000000      NaN   313.000000  215245.000000    NaN   

       Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood  \
count     91     1460        1460      1460      1460      1460         1460   
unique     2        4           4         2         5         3           25   
top     Grvl      Reg         Lvl    AllPub    Inside       Gtl        NAmes   
freq      50      925        1311      1459      1052      1382          225   
mean     NaN      NaN         NaN       NaN       NaN       NaN          NaN   
std      NaN      NaN         NaN       NaN       NaN       NaN          NaN   
min      NaN      NaN         NaN       NaN       NaN       NaN          NaN   
25%      NaN      NaN         NaN       NaN       NaN       NaN          NaN   
50%      NaN      NaN         NaN       NaN       NaN       NaN          NaN   
75%      NaN      NaN         NaN       NaN       NaN       NaN          NaN   
max      NaN      NaN         NaN       NaN       NaN       NaN          NaN   

       Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  \
count        1460       1460     1460       1460  1460.000000  1460.000000   
unique          9          8        5          8          NaN          NaN   
top          Norm       Norm     1Fam     1Story          NaN          NaN   
freq         1260       1445     1220        726          NaN          NaN   
mean          NaN        NaN      NaN        NaN     6.099315     5.575342   
std           NaN        NaN      NaN        NaN     1.382997     1.112799   
min           NaN        NaN      NaN        NaN     1.000000     1.000000   
25%           NaN        NaN      NaN        NaN     5.000000     5.000000   
50%           NaN        NaN      NaN        NaN     6.000000     5.000000   
75%           NaN        NaN      NaN        NaN     7.000000     6.000000   
max           NaN        NaN      NaN        NaN    10.000000     9.000000   

          YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd  \
count   1460.000000   1460.000000      1460     1460        1460        1460   
unique          NaN           NaN         6        8          15          16   
top             NaN           NaN     Gable  CompShg     VinylSd     VinylSd   
freq            NaN           NaN      1141     1434         515         504   
mean    1971.267808   1984.865753       NaN      NaN         NaN         NaN   
std       30.202904     20.645407       NaN      NaN         NaN         NaN   
min     1872.000000   1950.000000       NaN      NaN         NaN         NaN   
25%     1954.000000   1967.000000       NaN      NaN         NaN         NaN   
50%     1973.000000   1994.000000       NaN      NaN         NaN         NaN   
75%     2000.000000   2004.000000       NaN      NaN         NaN         NaN   
max     2010.000000   2010.000000       NaN      NaN         NaN         NaN   

       MasVnrType   MasVnrArea ExterQual ExterCond Foundation BsmtQual  \
count        1452  1452.000000      1460      1460       1460     1423   
unique          4          NaN         4         

In [5]:
df.isna().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFin

Limpando as colunas com muitos valores NA

In [6]:
df1 = df.drop(['Alley', 'MiscFeature', 'Fence', 'PoolQC', 'FireplaceQu','Id'], axis=1)

Substituindo valores nulo pela media e valores que mas aparece 

In [7]:
df1['MasVnrType'].fillna('None', inplace=True)
df1['BsmtQual'].fillna('TA', inplace=True)
df1['BsmtCond'].fillna('TA', inplace=True)
df1['BsmtExposure'].fillna('No', inplace=True)
df1['BsmtFinType1'].fillna('Unf', inplace=True)
df1['BsmtFinType2'].fillna('Unf', inplace=True)
df1['Electrical'].fillna('SBrkr', inplace=True)
df1['GarageType'].fillna('Attchd', inplace=True)
df1['GarageFinish'].fillna('Unf', inplace=True)
df1['GarageQual'].fillna('TA', inplace=True)
df1['GarageCond'].fillna('TA', inplace=True)
df1['LotFrontage'].fillna(df1['LotFrontage'].mean(), inplace=True)
df1['MasVnrArea'].fillna(df1['MasVnrArea'].mean(), inplace=True)
df1['GarageYrBlt'].fillna(df1['GarageYrBlt'].mean(), inplace=True)

In [8]:
df1.isna().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd

separando dados previsores e a classe que eu quero prever 

In [9]:
previsores = df1.drop('SalePrice',axis=1).values
classe = df1['SalePrice'].values

transformando dados categoricos em numeros

In [10]:
labelencoder = LabelEncoder()
previsores[:, 1] = labelencoder.fit_transform(previsores[:,1])

previsores[:, 4] = labelencoder.fit_transform(previsores[:,4])

previsores[:, 5] = labelencoder.fit_transform(previsores[:,5])

previsores[:, 6] = labelencoder.fit_transform(previsores[:,6])

previsores[:, 7] = labelencoder.fit_transform(previsores[:,7])

previsores[:, 8] = labelencoder.fit_transform(previsores[:,8])

previsores[:, 9] = labelencoder.fit_transform(previsores[:,9])

previsores[:, 10] = labelencoder.fit_transform(previsores[:,10])

previsores[:, 11] = labelencoder.fit_transform(previsores[:,11])

previsores[:, 12] = labelencoder.fit_transform(previsores[:,12])

previsores[:, 13] = labelencoder.fit_transform(previsores[:,13])

previsores[:, 14] = labelencoder.fit_transform(previsores[:,14])

previsores[:, 19] = labelencoder.fit_transform(previsores[:,19])

previsores[:, 20] = labelencoder.fit_transform(previsores[:,20])

previsores[:, 21] = labelencoder.fit_transform(previsores[:,21])

previsores[:, 22] = labelencoder.fit_transform(previsores[:,22])

previsores[:, 23] = labelencoder.fit_transform(previsores[:,23])

previsores[:, 25] = labelencoder.fit_transform(previsores[:,25])

previsores[:, 26] = labelencoder.fit_transform(previsores[:,26])

previsores[:, 27] = labelencoder.fit_transform(previsores[:,27])

previsores[:, 28] = labelencoder.fit_transform(previsores[:,28])

previsores[:, 29] = labelencoder.fit_transform(previsores[:,29])

previsores[:, 30] = labelencoder.fit_transform(previsores[:,30])

previsores[:, 31] = labelencoder.fit_transform(previsores[:,31])

previsores[:, 33] = labelencoder.fit_transform(previsores[:,33])

previsores[:, 37] = labelencoder.fit_transform(previsores[:,37])

previsores[:, 38] = labelencoder.fit_transform(previsores[:,38])

previsores[:, 39] = labelencoder.fit_transform(previsores[:,39])

previsores[:, 40] = labelencoder.fit_transform(previsores[:,40])

previsores[:, 51] = labelencoder.fit_transform(previsores[:,51])

previsores[:, 53] = labelencoder.fit_transform(previsores[:,53])

previsores[:, 54] = labelencoder.fit_transform(previsores[:,54])

previsores[:, 55] = labelencoder.fit_transform(previsores[:,55])

previsores[:, 57] = labelencoder.fit_transform(previsores[:,57])

previsores[:, 60] = labelencoder.fit_transform(previsores[:,60])

previsores[:, 61] = labelencoder.fit_transform(previsores[:,61])

previsores[:, 62] = labelencoder.fit_transform(previsores[:,62])

previsores[:, 72] = labelencoder.fit_transform(previsores[:,72])

previsores[:, 73] = labelencoder.fit_transform(previsores[:,73])

In [11]:
previsores

array([[60, 3, 65.0, ..., 2008, 8, 4],
       [20, 3, 80.0, ..., 2007, 8, 4],
       [60, 3, 68.0, ..., 2008, 8, 4],
       ...,
       [70, 3, 66.0, ..., 2010, 8, 4],
       [20, 3, 68.0, ..., 2010, 8, 4],
       [20, 3, 75.0, ..., 2008, 8, 4]], dtype=object)

fazendo uma padronização dos dados 

In [12]:
OneHotEncoder_tabela = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,4,5,6,7,8,9,10,11,12,13,14,19,20,21,22,23,25,26,27,28,29,30,31,33,37,38,39,40,51,53,54,55,57,60,61,62,72,73])], remainder='passthrough')
previsores = OneHotEncoder_tabela.fit_transform(previsores).toarray()
StandardScaler = StandardScaler()
previsores = StandardScaler.fit_transform(previsores)


In [13]:
previsores

array([[-0.08304548, -0.21585871, -0.10526316, ..., -0.08768781,
        -1.5991111 ,  0.13877749],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.08768781,
        -0.48911005, -0.61443862],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.08768781,
         0.99089135,  0.13877749],
       ...,
       [-0.08304548, -0.21585871, -0.10526316, ...,  4.95311151,
        -0.48911005,  1.64520971],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.08768781,
        -0.8591104 ,  1.64520971],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.08768781,
        -0.1191097 ,  0.13877749]])

separando dados de treino e teste

In [14]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size= 0.3,
                                                                  random_state= 0)

criando e treinando o modelo

In [15]:
arvore = DecisionTreeRegressor()
arvore.fit(x_treino, y_treino)

DecisionTreeRegressor()

testando o modelo

In [16]:
previsoes = arvore.predict(x_teste)
previsoes

array([143000., 152000., 117500., 219500.,  94500., 115000., 280000.,
       109900., 556581., 154000., 181134., 122500., 235000., 125000.,
       128900., 155000., 235000.,  84500., 142000., 274725., 117000.,
       144000.,  83000., 178000., 195000., 233230., 172400.,  75000.,
       360000., 120000., 143000., 189000., 141000., 336000., 410000.,
       176000., 266000., 130250., 219500., 301500., 149500., 155000.,
       155835., 233230., 315000., 141000., 117500., 131000., 171000.,
       135750., 426000., 145000., 132000.,  81000., 311872.,  81000.,
       112000., 212000., 155000., 115000., 159500., 128900., 139000.,
       139950., 175000., 159000., 151500., 250580., 110000., 165000.,
       176000., 120000.,  93500., 280000., 135750., 225000., 118000.,
       135000., 290000., 168500., 137000., 120000., 120000., 156000.,
       139000., 194500., 125500., 202500., 177500., 128900., 207500.,
       185000., 176000., 235000., 174000., 143000., 206000., 157500.,
       120000., 1575

metrica de acuracy do modelo

In [17]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_teste, previsoes)

24783.447488584476